### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by vkorf** [tbtz/immo-check#2]
Failed to pass "Immo Check setup was successful! ✅" step.
It was working last year though.

**Comment by tbtz** [comment]
Hey @vkorf, sorry for the late answer, somehow i wasn't notified about new issues.
Today i found some time to make it work again.
Immobilienscout changed their website, so the Bot wasn't working anymore, but now it should work again.

I released a [new version including the fixes](https://github.com/tbtz/immo-check/releases/latest).

Please give me an update if you were able to get it working again.

**Comment by vkorf** [comment]
Hi @tbtz, thank you for your time, it works now.
