### ISSUE TITLE
Captchas

### ISSUE THREAD

**Issue by vclemens1** [tbtz/immo-check#3]
Hey, 

Thank you for the great tool. It generally works fine for me. However, sometimes I get an IFTTT notification on my iPhone that informs me that a captcha needs to be solved.

When I'm at home that's fine but when on the go I'm unable to solve it.

Is there a way to make it work on the go? Either by solving the captcha on the phone somehow or avoiding it in the first place.

Thanks so much!

Cheers

Note: I manually changed the "reload page" time from 60s to 10s in the .js file.

**Comment by vclemens1** [comment]
I solved it: Chrome Remote Desktop.

It allows you to access your computer remotely, including solving the captcha.

However, you have to authorise pretty much everything, probably not the smartest move from a privacy perspective 🫠 

Cheers

**Comment by tbtz** [comment]
Hey @vclemens1, 
great to hear that you solved the problem!
I also struggled with that.
Thanks for sharing your idea! 💡
